# Base styles and structure of site.
INHERIT: ./base.yml

# Project Information
site_name: IBM Cloud MCP Servers
site_url: "https://pages.github.com/IBM-Cloud/mcp/"
site_description: "IBM MCP Servers Documentation"
site_author: "Maxim Shelepov"

# Repository Information
repo_name: "IBM-Cloud/mcp"
repo_url: "https://github.com/IBM-Cloud/mcp"

# Main Site Navigation.
nav:
  - Home: index.md
  - Documentation:
    - Overview: overview.md
    - Servers:
      - Core MCP Server: servers/core.md
      - Serverless MCP Server: servers/serverless.md
      - VPC MCP Server: servers/vpc.md
      - Kubernetes & OpenShift MCP Server: servers/kubernetes.md
      - Cloud Automation MCP Server: servers/cloud-automation.md

# Copyright
copyright: Copyright (c) 2025 IBM Corporation.

# Home Page Content.
home_tagline: Enhance your LLM üß† with Tools üõ†Ô∏è from IBM Cloud ‚òÅÔ∏è
home_description: |
  With the help of the MCP protocol, a standardized protocol for LLM to external server communication, connect your client LLMs with the tools and capabilities you need provided by IBM cloud.
home_video_demo_url: ./assets/DEMO_IBMCloud_MCP_for_VPC.mov

home_button_text: Get Started &#10142;
home_button_url: overview
home_button_icon: .icons/octicons/octicons/arrow/right/16

# Draft Pages.
# Notes:
# - To exclude from nav, comment out the page above in the "nav:" section.
# draft_docs: |
#   servers/core.md
#   other/other.md

# Extra links as icons at the bottom of the page
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IBM-Cloud/mcp

### ------- FOR REFERENCE ------- ###
# Theme settings
# theme:
#   language: en
#   features:
#     - announce.dismiss # Button to dismiss the current temporary announcement
#     - content.action.edit
#     - content.action.feedback
#     # - content.action.view
#     - content.code.annotate # Attach arbitrary content to specific sections of code blocks by adding numeric markers
#     - content.code.copy # Button to allow the user to copy a code block's contents to the clipboard
#     # - content.tabs.link
#     # - navigation.expand     # Expand left sidebar by default
#     - navigation.indexes # Attach documents to sections, useful for providing overview pages
#     - navigation.instant # Single page instant refresh
#     # - navigation.sections   # Top level tabs rendered in sidebar
#     - navigation.tabs # Navigation tabs across top. Comment this out to have navigation on the left
#     - navigation.tabs.sticky # Tab always displayed
#     - navigation.top # Back-to-top button. Rendered centered and just below the header
#     - navigation.tracking # URL updated with active anchor
#     - search.share
#     - search.suggest
#     - toc.integrate # Integrate page TOC in left sidebar - wider page
#   icon:
#     edit: "material/pencil-outline"

# markdown_extensions:
#   pymdownx.magiclink:
#     provider: "github"
#     repo_url_shortener: true
#     repo_url_shorthand: false
#     social_url_shorthand: true
#     user: ibm
#     repo: ibm/mcp-context-forge
#   toc:
#     permalink: true
#     toc_depth: 3

# plugins:
#   # Built-in blog plugin - see https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
#   # blog:
#   #     blog_dir: "blog"
#   #     pagination_per_page: 5
#   #     post_date_format: full
#   #     post_url_date_format: yyyy/MM/dd
#   # Allow Tags on the pages - see https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
#   # tags:
#   #     tags_file: tags.md
#   # Configure the PDF export plugin - see https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
#   with-pdf: # This creates a single PDF document for the whole site
#     author: Mihai Criveti
#     copyright: Copyright &copy; Apache 2.0
#     cover: true
#     back_cover: false
#     #
#     cover_title: MCP Context Forge - MCP Gateway
#     cover_subtitle: MCP Gateway Documentation
#     cover_logo: "theme/logo.png"
#     #custom_template_path: TEMPLATES PATH
#     #
#     toc_title: Contents
#     # heading_shift: false
#     toc_level: 2
#     #ordered_chapter_level: 2
#     #excludes_children:
#     #    - 'release-notes/:upgrading'
#     #    - 'release-notes/:changelog'
#     #
#     exclude_pages:
#       - "blog"
#     #convert_iframe:
#     #    - src: IFRAME SRC
#     #      img: POSTER IMAGE URL
#     #      text: ALTERNATE TEXT
#     #    - src: ...
#     #two_columns_level: 3
#     #
#     # render_js: true
#     #headless_chrome_path: headless-chromium
#     #
#     output_path: ./pdf/mcpgateway-docs.pdf
#     enabled_if_env: ENABLE_PDF_EXPORT
#     #
#     debug_html: true
#     #show_anchors: true
#     verbose: false